include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    public_member_api_docs: ignore
    comment_references: ignore
    sort_pub_dependencies: ignore
    flutter_style_todos: false