name: task_management
description: "taskup is an open source task management app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4  
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  flutter_riverpod: ^2.5.1
  logger: ^2.0.2 
  firebase_ui_firestore: ^1.6.4
  equatable: ^2.0.5
  riverpod_annotation: ^2.3.5
  speech_to_text: ^6.2.0
  flutter_tts: ^3.3.0
  
  # Utility & Widget 
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0  
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  validify: ^0.0.3
  
  # Config
  easy_localization: ^3.0.3  

  json_annotation: ^4.9.0

  # Modules
  core:
    path: module/core
  gen:
    path: module/gen
  widget:
    path: module/widget  
  firebase_core_platform_interface: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0  
  mockito: ^5.4.4
  
flutter:

  uses-material-design: true

  assets:
    - assets/translations/
