name: task_management
description: "taskup is an open-source task management app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  # Core Flutter dependencies
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4  
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  flutter_launcher_icons:

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Utility libraries
  equatable: ^2.0.5
  speech_to_text: ^6.2.0
  flutter_tts: ^3.3.0
  
  # UI components and utilities
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0  
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  validify: ^0.0.3
  shimmer: ^3.0.0
  fl_chart: ^0.69.0

  # Localization
  easy_localization: ^3.0.3  

  # JSON serialization
  json_annotation: ^4.9.0

  # Caching
  hive: ^2.2.3
  path_provider: ^2.1.4

  # Modularization
  core:
    path: module/core
  gen:
    path: module/gen
  widget:
    path: module/widget  

flutter_launcher_icons:
  image_path: "assets/images/taskup.png"
  android: false
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0  
  mockito: ^5.4.4
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
